/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import {PerspectiveCamera} from "@react-three/drei";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/J1ZFFuOUPL5y8MmS/scene.splinecode",
  );
  return (
    <>
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <PerspectiveCamera
            name="Camera"
            makeDefault={true}
            zoom={1.7}
            far={100000}
            near={18}
            fov={35}
            up={[0, 1, 0]}
            position={[-215.1, 228.18, 213.05]}
            rotation={[-0.75, -0.59, -0.48]}
          />
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={1.02}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-5000}
            shadow-camera-right={5000}
            shadow-camera-top={5000}
            shadow-camera-bottom={-5000}
            position={[-165.95, 293.9, -198.32]}
          />
          <group name="Group" position={[-5.4, 32.6, -6.89]}>
            <group
              name="ChargerTermina1_MotionLESS"
              position={[-19.6, -112.6, 288.89]}
              scale={113.1}
            >
              <mesh
                name="Screen"
                geometry={nodes.Screen.geometry}
                material={nodes.Screen.material}
                castShadow
                receiveShadow
                position={[0.8, 1.17, -2.88]}
                rotation={[0, 0.5, 0]}
                scale={[0.19, 0.14, 0.14]}
              />
              <group
                name="EV_charger_type_2_plug_Product_v21"
                position={[2.54, 0.35, -3.83]}
                rotation={[Math.PI / 2, 0, -0.5]}
                scale={0.01}
              >
                <mesh
                  name="Body21"
                  geometry={nodes.Body21.geometry}
                  material={nodes.Body21.material}
                  castShadow
                  receiveShadow
                  position={[0, 0, 0]}
                  scale={10}
                />
                <mesh
                  name="Body23"
                  geometry={nodes.Body23.geometry}
                  material={nodes.Body23.material}
                  castShadow
                  receiveShadow
                  position={[0, 0, 0]}
                  scale={10}
                />
                <mesh
                  name="Body24"
                  geometry={nodes.Body24.geometry}
                  material={nodes.Body24.material}
                  castShadow
                  receiveShadow
                  position={[0, 0, 0]}
                  scale={10}
                />
                <mesh
                  name="Head001"
                  geometry={nodes.Head001.geometry}
                  material={nodes.Head001.material}
                  castShadow
                  receiveShadow
                  position={[-170, 0, 0]}
                  rotation={[0, 0, 0]}
                  scale={10}
                />
                <group name="Input_Protect">
                  <mesh
                    name="Body1003"
                    geometry={nodes.Body1003.geometry}
                    material={nodes.Body1003.material}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    scale={10}
                  />
                  <mesh
                    name="Body1006"
                    geometry={nodes.Body1006.geometry}
                    material={nodes.Body1006.material}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    scale={10}
                  />
                  <mesh
                    name="Body2002"
                    geometry={nodes.Body2002.geometry}
                    material={nodes.Body2002.material}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    scale={10}
                  />
                  <mesh
                    name="Body2003"
                    geometry={nodes.Body2003.geometry}
                    material={nodes.Body2003.material}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    scale={10}
                  />
                  <mesh
                    name="Body3001"
                    geometry={nodes.Body3001.geometry}
                    material={nodes.Body3001.material}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    scale={10}
                  />
                  <mesh
                    name="Body3002"
                    geometry={nodes.Body3002.geometry}
                    material={nodes.Body3002.material}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    scale={10}
                  />
                  <mesh
                    name="Body4002"
                    geometry={nodes.Body4002.geometry}
                    material={nodes.Body4002.material}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    scale={10}
                  />
                  <mesh
                    name="Body4003"
                    geometry={nodes.Body4003.geometry}
                    material={nodes.Body4003.material}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    scale={10}
                  />
                  <mesh
                    name="Body5001"
                    geometry={nodes.Body5001.geometry}
                    material={nodes.Body5001.material}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    scale={10}
                  />
                  <mesh
                    name="Body5002"
                    geometry={nodes.Body5002.geometry}
                    material={nodes.Body5002.material}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    scale={10}
                  />
                  <mesh
                    name="Body7001"
                    geometry={nodes.Body7001.geometry}
                    material={nodes.Body7001.material}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    scale={10}
                  />
                  <mesh
                    name="Body7002"
                    geometry={nodes.Body7002.geometry}
                    material={nodes.Body7002.material}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    scale={10}
                  />
                  <mesh
                    name="Body1002"
                    geometry={nodes.Body1002.geometry}
                    material={nodes.Body1002.material}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    rotation={[0, 0, 0]}
                    scale={10}
                  />
                  <mesh
                    name="Body1005"
                    geometry={nodes.Body1005.geometry}
                    material={nodes.Body1005.material}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    rotation={[0, 0, 0]}
                    scale={10}
                  />
                  <group name="Lock" position={[-204, 0.5, 0]}>
                    <mesh
                      name="Body1"
                      geometry={nodes.Body1.geometry}
                      material={nodes.Body1.material}
                      castShadow
                      receiveShadow
                      position={[0, 0, 0]}
                      scale={10}
                    />
                    <mesh
                      name="Body2"
                      geometry={nodes.Body2.geometry}
                      material={nodes.Body2.material}
                      castShadow
                      receiveShadow
                      position={[0, 0, 0]}
                      scale={10}
                    />
                    <mesh
                      name="Body4"
                      geometry={nodes.Body4.geometry}
                      material={nodes.Body4.material}
                      castShadow
                      receiveShadow
                      position={[0, 0, 0]}
                      scale={10}
                    />
                  </group>
                  <group name="shell">
                    <mesh
                      name="Body1004"
                      geometry={nodes.Body1004.geometry}
                      material={nodes.Body1004.material}
                      castShadow
                      receiveShadow
                      position={[-206.76, 0.03, -59.91]}
                      scale={10}
                    />
                  </group>
                  <group name="pins" position={[-170, 0, 0]}>
                    <mesh
                      name="Body1001"
                      geometry={nodes.Body1001.geometry}
                      material={nodes.Body1001.material}
                      castShadow
                      receiveShadow
                      position={[0, 0, 0]}
                      scale={10}
                    />
                    <mesh
                      name="Body10"
                      geometry={nodes.Body10.geometry}
                      material={nodes.Body10.material}
                      castShadow
                      receiveShadow
                      position={[0, 0, 0]}
                      scale={10}
                    />
                    <mesh
                      name="Body11"
                      geometry={nodes.Body11.geometry}
                      material={nodes.Body11.material}
                      castShadow
                      receiveShadow
                      position={[0, 0, 0]}
                      scale={10}
                    />
                    <mesh
                      name="Body2001"
                      geometry={nodes.Body2001.geometry}
                      material={nodes.Body2001.material}
                      castShadow
                      receiveShadow
                      position={[0, 0, 0]}
                      scale={10}
                    />
                    <mesh
                      name="Body3"
                      geometry={nodes.Body3.geometry}
                      material={nodes.Body3.material}
                      castShadow
                      receiveShadow
                      position={[0, 0, 0]}
                      scale={10}
                    />
                    <mesh
                      name="Body4001"
                      geometry={nodes.Body4001.geometry}
                      material={nodes.Body4001.material}
                      castShadow
                      receiveShadow
                      position={[0, 0, 0]}
                      scale={10}
                    />
                    <mesh
                      name="Body5"
                      geometry={nodes.Body5.geometry}
                      material={nodes.Body5.material}
                      castShadow
                      receiveShadow
                      position={[0, 0, 0]}
                      scale={10}
                    />
                    <mesh
                      name="Body6"
                      geometry={nodes.Body6.geometry}
                      material={nodes.Body6.material}
                      castShadow
                      receiveShadow
                      position={[0, 0, 0]}
                      scale={10}
                    />
                    <mesh
                      name="Body7"
                      geometry={nodes.Body7.geometry}
                      material={nodes.Body7.material}
                      castShadow
                      receiveShadow
                      position={[0, 0, 0]}
                      scale={10}
                    />
                    <mesh
                      name="Body8"
                      geometry={nodes.Body8.geometry}
                      material={nodes.Body8.material}
                      castShadow
                      receiveShadow
                      position={[0, 0, 0]}
                      scale={10}
                    />
                    <mesh
                      name="Body9"
                      geometry={nodes.Body9.geometry}
                      material={nodes.Body9.material}
                      castShadow
                      receiveShadow
                      position={[0, 0, 0]}
                      scale={10}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
          <hemisphereLight
            name="Default Ambient Light"
            intensity={0.75}
            color="#eaeaea"
          />
        </scene>
      </group>
    </>
  );
}
